routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

# Auth and dashboard
Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

# Customers
Route::resource('customers', \App\Modules\Customers\Controllers\CustomersController::class);
Route::get('/customers/delete/{customer}', [\App\Modules\Customers\Controllers\CustomersController::class, 'delete'])->name('customers.delete');

# Groups
Route::resource('groups', \App\Modules\Groups\Controllers\GroupsController::class);
Route::get('/groups/delete/{group}', [\App\Modules\Groups\Controllers\GroupsController::class, 'delete'])->name('groups.delete');
Route::get('/groups/new-mail/{group}', [\App\Modules\Groups\Controllers\GroupsController::class, 'newMail'])->name('groups.new_mail');
Route::post('/groups/send-mail/{group}', [\App\Modules\Groups\Controllers\GroupsController::class, 'sendMail'])->name('groups.send_mail');

# E-mail templates
Route::resource('email-templates', \App\Modules\EmailTemplates\Controllers\EmailTemplatesController::class);
Route::get('/email-templates/delete/{email_template}', [\App\Modules\EmailTemplates\Controllers\EmailTemplatesController::class, 'delete'])->name('email-templates.delete');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/customers/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Create customer') }} | <a href="{{ route('customers.index') }}">Customers</a></div>

                <div class="card-body">
                    @include('partials.success_error_message')
                    <form action="{{ route('customers.store') }}" method="POST">
                        {!! csrf_field() !!}
                        {!! method_field('POST') !!}
                        @include('customers.form', ['customer' => false])
                        <div class="form-group">
                            <button class="btn btn-success btn-block">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/customers/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Edit customer - '.$customer->firstname) }} | <a href="{{ route('customers.index') }}">Customers</a></div>
                <div class="card-body">
                    @include('partials.success_error_message')
                    <form action="{{ route('customers.update', ['customer' => $customer->id]) }}" method="POST">
                        {!! csrf_field() !!}
                        {!! method_field('PATCH') !!}
                        <input type="hidden" name="id" value="{{ $customer->id }}">
                        @include('customers.form', ['customer' => $customer])
                        <div class="form-group">
                            <button class="btn btn-success btn-block">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/customers/form.blade.php
<div class="form-group">
    <label>Email</label>
    <input type="email" class="form-control" name="email" value="{{ $customer ? $customer->email : old('email') }}">
</div>
<div class="form-group">
    <label>Firstname</label>
    <input type="text" class="form-control" name="firstname" value="{{$customer ? $customer->firstname :  old('firstname') }}">
</div>
<div class="form-group">
    <label>Lastname</label>
    <input type="text" class="form-control" name="lastname" value="{{$customer ? $customer->lastname :  old('lastname') }}">
</div>
<div class="form-group">
    <label>Birthday</label>
    <input type="text" class="form-control" name="birthday" value="{{$customer ? $customer->birthday :  old('birthday') }}">
</div>
<div class="form-group">
    <label>Group</label>
    <select class="form-control" name="customerGroups[]" multiple>
        @if($groups)
            @foreach($groups as $group)
                <option value="{{ $group->id }}" {{ isset($customerGroups) && in_array($group->id, $customerGroups) ? 'selected' : '' }}>{{ $group->name }}</option>
            @endforeach
        @endif
    </select>
</div>
<div class="radio">
    <label><input type="radio" name="sex" value="0" {{ $customer ? ($customer->sex == 0 ? 'checked' : '') : (old('sex') == 0 ? 'checked' : '') }}> Man</label>
</div>
<div class="radio">
    <label><input type="radio" name="sex" value="1" {{ $customer ? ($customer->sex == 1 ? 'checked' : '') : (old('sex') == 1 ? 'checked' : '') }}> Woman</label>
</div>

resources/views/customers/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Customers') }} | <a href="{{ route('customers.create') }}">New Customer</a></div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    @include('partials.success_error_message')
                    @if($customers)
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered">
                                <thead>
                                <th>ID</th>
                                <th>E-mail</th>
                                <th>Firstname</th>
                                <th>Lastname</th>
                                <th>Sex</th>
                                <th>Birthday</th>
                                <th>Groups</th>
                                <th>Operations</th>
                                </thead>
                                @foreach($customers as $customer)
                                    <tr>
                                        <td>{{ $customer->id }}</td>
                                        <td>{{ $customer->email }}</td>
                                        <td>{{ $customer->firstname }}</td>
                                        <td>{{ $customer->lastname }}</td>
                                        <td>{{ $customer->sex == 0 ? 'Woman' : 'Man' }}</td>
                                        <td>{{ $customer->birthday }}</td>
                                        <td>
                                            @if($customer->groups)
                                                @foreach($customer->groups as $group)
                                                 {{ $group->name }},
                                                @endforeach
                                            @endif
                                        </td>
                                        <td>
                                            <a href="{{ route('customers.edit', ['customer' => $customer->id]) }}">Edit</a> |
                                            <a href="{{ route('customers.delete', ['customer' => $customer->id]) }}">Delete</a>
                                        </td>
                                    </tr>
                                @endforeach
                            </table>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/email-templates/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Create template') }} | <a href="{{ route('email-templates.index') }}">E-mail templates</a></div>

                <div class="card-body">
                    @include('partials.success_error_message')
                    <form action="{{ route('email-templates.store') }}" method="POST">
                        {!! csrf_field() !!}
                        {!! method_field('POST') !!}
                        @include('email-templates.form', ['template' => false])
                        <div class="form-group">
                            <button class="btn btn-success btn-block">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/email-templates/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Edit template - '.$template->name) }} | <a href="{{ route('email-templates.index') }}">E-mail templates</a></div>
                <div class="card-body">
                    @include('partials.success_error_message')
                    <form action="{{ route('email-templates.update', ['email_template' => $template->id]) }}" method="POST">
                        {!! csrf_field() !!}
                        {!! method_field('PATCH') !!}
                        <input type="hidden" name="id" value="{{ $template->id }}">
                        @include('email-templates.form', ['template' => $template])
                        <div class="form-group">
                            <button class="btn btn-success btn-block">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/email-templates/form.blade.php
<div class="form-group">
    <label>Template unique code (no spaces, with letters and underscore. Example: mass_email)</label>
    <input type="text" class="form-control" name="code" value="{{$template ? $template->code :  old('code') }}">
</div>
<div class="form-group">
    <label>Template name</label>
    <input type="text" class="form-control" name="name" value="{{$template ? $template->name :  old('name') }}">
</div>
<div class="form-group">
    <label>Subject (<b>Example: E-mail from {=site=}</b>)</label>
    <input type="text" class="form-control" name="subject" value="{{$template ? $template->subject :  old('subject') }}">
</div>
<div class="form-group">
    <label>Text (<b>Example: Hi, dear {=user=}</b>)</label>
    <textarea class="form-control" name="template" rows="6">{!! $template ? $template->template :  old('template') !!}</textarea>
</div>

resources/views/email-templates/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('E-mail templates') }} | <a href="{{ route('email-templates.create') }}">New template</a></div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    @include('partials.success_error_message')
                    @if($templates)
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered">
                                <thead>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Operations</th>
                                </thead>
                                @foreach($templates as $template)
                                    <tr>
                                        <th>{{ $template->id }}</th>
                                        <th>{{ $template->name }}</th>
                                        <th>
                                            <a href="{{ route('email-templates.edit', ['email_template' => $template->id]) }}">Edit</a> |
                                            <a href="{{ route('email-templates.delete', ['email_template' => $template->id]) }}">Delete</a>
                                        </th>
                                    </tr>
                                @endforeach
                            </table>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/groups/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Create group') }} | <a href="{{ route('groups.index') }}">Groups</a></div>

                <div class="card-body">
                    @include('partials.success_error_message')
                    <form action="{{ route('groups.store') }}" method="POST">
                        {!! csrf_field() !!}
                        {!! method_field('POST') !!}
                        @include('groups.form', ['group' => false])
                        <div class="form-group">
                            <button class="btn btn-success btn-block">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/groups/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Edit group - '.$group->name) }} | <a href="{{ route('groups.index') }}">Groups</a></div>
                <div class="card-body">
                    @include('partials.success_error_message')
                    <form action="{{ route('groups.update', ['group' => $group->id]) }}" method="POST">
                        {!! csrf_field() !!}
                        {!! method_field('PATCH') !!}
                        <input type="hidden" name="id" value="{{ $group->id }}">
                        @include('groups.form', ['group' => $group])
                        <div class="form-group">
                            <button class="btn btn-success btn-block">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/groups/form.blade.php
<div class="form-group">
    <label>Group name</label>
    <input type="text" class="form-control" name="name" value="{{$group ? $group->name :  old('name') }}">
</div>

resources/views/groups/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Groups') }} | <a href="{{ route('groups.create') }}">New Group</a></div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    @include('partials.success_error_message')
                    @if($groups)
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered">
                                <thead>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Operations</th>
                                </thead>
                                @foreach($groups as $group)
                                    <tr>
                                        <th>{{ $group->id }}</th>
                                        <th>{{ $group->name }}</th>
                                        <th>
                                            <a href="{{ route('groups.edit', ['group' => $group->id]) }}">Edit</a> |
                                            <a href="{{ route('groups.delete', ['group' => $group->id]) }}">Delete</a> |
                                            <a href="{{ route('groups.new_mail', ['group' => $group->id]) }}">New mail</a>
                                        </th>
                                    </tr>
                                @endforeach
                            </table>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/groups/new_mail.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Send email to '.$group->name.' customers') }} | <a href="{{ route('groups.index') }}">Groups</a></div>

                <div class="card-body">
                    @include('partials.success_error_message')
                    <form action="{{ route('groups.send_mail', ['group' => $group]) }}" method="POST">
                        {!! csrf_field() !!}
                        {!! method_field('POST') !!}
                        <div class="form-group">
                            <label>E-mail template</label>
                            <select class="form-control" name="template_id">
                                @if($templates)
                                    @foreach($templates as $template)
                                        <option value="{{ $template->id }}" {{ old('template_id') }}>{{ $template->name }}</option>
                                    @endforeach
                                @endif
                            </select>
                        </div>
                        <div class="radio">
                            <label><input type="radio" name="delay" value="0" {{ (old('delay') == 0 ? 'checked' : '') }}> Send immediately</label>
                        </div>
                        <div class="radio">
                            <label><input type="radio" name="delay" value="1" {{ (old('delay') == 1 ? 'checked' : '') }}> Send with delay</label>
                        </div>
                        <div class="form-group">
                            <label>Delay time in minutes</label>
                            <input type="number" min="0" class="form-control" name="time" value="{{ old('time') ? old('time') : 0 }}">
                        </div>
                        <div class="form-group">
                            <button class="btn btn-success btn-block">Send</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('Hi, '.auth()->user()->name) }}
                    <hr>
                    <ul class="list-group">
                        <li class="list-group-item">
                            <a href="{{ route('customers.index') }}">Customers</a>
                        </li>
                        <li class="list-group-item">
                            <a href="{{ route('groups.index') }}">Groups</a>
                        </li>
                        <li class="list-group-item">
                            <a href="{{ route('email-templates.index') }}">E-mail templates</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="/">{{ __('Home') }}</a>
                            </li>
                        @else
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('home') }}">{{ __('Dashboard') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('customers.index') }}">{{ __('Customers') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('groups.index') }}">{{ __('Groups') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('email-templates.index') }}">{{ __('E-mail templates') }}</a>
                            </li>
                        @endguest
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/partials/success_error_message.blade.php
@if (session('message'))
    <div class="alert alert-success" role="alert">
        {{ session('message') }}
    </div>
@endif
@if ($errors->any())
    <ul class="list-group mb-3">
        @foreach ($errors->all() as $error)
            <li class="list-group-item list-group-item-warning">{{ $error }}</li>
        @endforeach
    </ul>

@endif